<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class DataSourceSeeder extends Seeder
{
    /**
     * Seed initial data sources.
     */
    public function run(): void
    {
        $sources = [
            [
                'id' => Str::uuid()->toString(),
                'code' => 'dhis2_health',
                'name' => 'DHIS2 Health Data',
                'description' => 'District Health Information System - health indicators',
                'organization_id' => null,
                'source_type' => 'api',
                'provider' => 'DHIS2',
                'api_url' => null,
                'api_auth_type' => null,
                'api_credentials_encrypted' => null,
                'data_format' => 'json',
                'update_frequency' => 'daily',
                'coverage_countries' => json_encode(['CM']),
                'coverage_regions' => null,
                'active' => true,
                'last_sync_at' => null,
                'last_sync_status' => null,
                'last_sync_error' => null,
                'consecutive_failures' => 0,
                'reliability_score' => 0.95,
                'data_quality_score' => 0.90,
                'total_records_synced' => 0,
                'sync_config' => null,
                'auto_sync' => false,
                'documentation_url' => 'https://docs.dhis2.org/en/develop/using-the-api/dhis-core-version-240/introduction.html',
                'contact_info' => null,
                'metadata' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'code' => 'chirps_rainfall',
                'name' => 'CHIRPS Rainfall Data',
                'description' => 'Climate Hazards Group InfraRed Precipitation with Station data',
                'organization_id' => null,
                'source_type' => 'api',
                'provider' => 'UCSB Climate Hazards Group',
                'api_url' => 'https://data.chc.ucsb.edu/products/CHIRPS-2.0/',
                'api_auth_type' => 'none',
                'api_credentials_encrypted' => null,
                'data_format' => 'geojson',
                'update_frequency' => 'daily',
                'coverage_countries' => json_encode(['CM', 'NG', 'TD', 'CF']),
                'coverage_regions' => null,
                'active' => true,
                'last_sync_at' => null,
                'last_sync_status' => null,
                'last_sync_error' => null,
                'consecutive_failures' => 0,
                'reliability_score' => 1.00,
                'data_quality_score' => 0.95,
                'total_records_synced' => 0,
                'sync_config' => null,
                'auto_sync' => false,
                'documentation_url' => 'https://www.chc.ucsb.edu/data/chirps',
                'contact_info' => null,
                'metadata' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'code' => 'acled_conflict',
                'name' => 'ACLED Conflict Events',
                'description' => 'Armed Conflict Location & Event Data Project',
                'organization_id' => null,
                'source_type' => 'api',
                'provider' => 'ACLED',
                'api_url' => 'https://api.acleddata.com/acled/read',
                'api_auth_type' => 'api_key',
                'api_credentials_encrypted' => null,
                'data_format' => 'json',
                'update_frequency' => 'weekly',
                'coverage_countries' => json_encode(['CM', 'NG', 'TD', 'CF', 'NE']),
                'coverage_regions' => null,
                'active' => true,
                'last_sync_at' => null,
                'last_sync_status' => null,
                'last_sync_error' => null,
                'consecutive_failures' => 0,
                'reliability_score' => 0.98,
                'data_quality_score' => 0.92,
                'total_records_synced' => 0,
                'sync_config' => null,
                'auto_sync' => false,
                'documentation_url' => 'https://apidocs.acleddata.com/',
                'contact_info' => null,
                'metadata' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'code' => 'who_disease_surveillance',
                'name' => 'WHO Disease Surveillance',
                'description' => 'World Health Organization disease outbreak data',
                'organization_id' => null,
                'source_type' => 'api',
                'provider' => 'WHO',
                'api_url' => null,
                'api_auth_type' => null,
                'api_credentials_encrypted' => null,
                'data_format' => 'json',
                'update_frequency' => 'daily',
                'coverage_countries' => null,
                'coverage_regions' => null,
                'active' => false,
                'last_sync_at' => null,
                'last_sync_status' => null,
                'last_sync_error' => null,
                'consecutive_failures' => 0,
                'reliability_score' => 1.00,
                'data_quality_score' => null,
                'total_records_synced' => 0,
                'sync_config' => null,
                'auto_sync' => false,
                'documentation_url' => 'https://www.who.int/emergencies/disease-outbreak-news',
                'contact_info' => null,
                'metadata' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'code' => 'unicef_mics',
                'name' => 'UNICEF MICS Surveys',
                'description' => 'Multiple Indicator Cluster Surveys - household indicators',
                'organization_id' => null,
                'source_type' => 'file_upload',
                'provider' => 'UNICEF',
                'api_url' => null,
                'api_auth_type' => null,
                'api_credentials_encrypted' => null,
                'data_format' => 'csv',
                'update_frequency' => 'quarterly',
                'coverage_countries' => null,
                'coverage_regions' => null,
                'active' => true,
                'last_sync_at' => null,
                'last_sync_status' => null,
                'last_sync_error' => null,
                'consecutive_failures' => 0,
                'reliability_score' => 1.00,
                'data_quality_score' => 0.98,
                'total_records_synced' => 0,
                'sync_config' => null,
                'auto_sync' => false,
                'documentation_url' => 'https://mics.unicef.org/',
                'contact_info' => null,
                'metadata' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'code' => 'kobo_field_surveys',
                'name' => 'KoboToolbox Field Surveys',
                'description' => 'Mobile data collection from field workers',
                'organization_id' => null,
                'source_type' => 'api',
                'provider' => 'KoboToolbox',
                'api_url' => null,
                'api_auth_type' => null,
                'api_credentials_encrypted' => null,
                'data_format' => 'json',
                'update_frequency' => 'realtime',
                'coverage_countries' => null,
                'coverage_regions' => null,
                'active' => false,
                'last_sync_at' => null,
                'last_sync_status' => null,
                'last_sync_error' => null,
                'consecutive_failures' => 0,
                'reliability_score' => 0.85,
                'data_quality_score' => null,
                'total_records_synced' => 0,
                'sync_config' => null,
                'auto_sync' => false,
                'documentation_url' => 'https://support.kobotoolbox.org/api.html',
                'contact_info' => null,
                'metadata' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'code' => 'manual_entry',
                'name' => 'Manual Data Entry',
                'description' => 'Data entered directly by users through admin interface',
                'organization_id' => null,
                'source_type' => 'manual_entry',
                'provider' => null,
                'api_url' => null,
                'api_auth_type' => null,
                'api_credentials_encrypted' => null,
                'data_format' => null,
                'update_frequency' => 'on_demand',
                'coverage_countries' => null,
                'coverage_regions' => null,
                'active' => true,
                'last_sync_at' => null,
                'last_sync_status' => null,
                'last_sync_error' => null,
                'consecutive_failures' => 0,
                'reliability_score' => 0.80,
                'data_quality_score' => null,
                'total_records_synced' => 0,
                'sync_config' => null,
                'auto_sync' => false,
                'documentation_url' => null,
                'contact_info' => null,
                'metadata' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'code' => 'csv_import',
                'name' => 'CSV File Import',
                'description' => 'Batch import from CSV/Excel files',
                'organization_id' => null,
                'source_type' => 'file_upload',
                'provider' => null,
                'api_url' => null,
                'api_auth_type' => null,
                'api_credentials_encrypted' => null,
                'data_format' => 'csv',
                'update_frequency' => 'on_demand',
                'coverage_countries' => null,
                'coverage_regions' => null,
                'active' => true,
                'last_sync_at' => null,
                'last_sync_status' => null,
                'last_sync_error' => null,
                'consecutive_failures' => 0,
                'reliability_score' => 0.75,
                'data_quality_score' => null,
                'total_records_synced' => 0,
                'sync_config' => null,
                'auto_sync' => false,
                'documentation_url' => null,
                'contact_info' => null,
                'metadata' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('data_sources')->insert($sources);

        $this->command->info('✔ Seeded ' . count($sources) . ' data sources');
    }
}