<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * RiskScore Model
 *
 * Stores climate risk assessments per district.
 * Generated by the Python risk engine and stored
 * by the Laravel alert generation pipeline.
 *
 * Each record represents one hazard assessment
 * at one point in time for one district.
 *
 * @property string $id
 * @property string $district_id
 * @property string $hazard_type
 * @property float  $score
 * @property float  $confidence
 * @property array  $metadata
 * @property string $scored_at
 */
class RiskScore extends Model
{
    use HasFactory, HasUuids;

    protected $keyType = 'string';
    public $incrementing = false;

    protected $table = 'risk_scores';

    protected $fillable = [
        'district_id',
        'hazard_type_id',
        'score',
        'risk_level',
        'reason',
        'children_at_risk',
        'time_window_days',
        'input_data',
        'risk_engine',
        'engine_version',
        'calculated_by_user_id',
        'calculation_source',
        'calculated_at',
        'alert_id',
        'metadata',
    ];

    /**
     * Attribute casting.
     *
     * CRITICAL: metadata must be cast to array.
     * Without this, JSON from Python engine will
     * not be properly stored or retrieved.
     */
    protected $casts = [
        'score'            => 'float',
        'children_at_risk' => 'integer',
        'time_window_days' => 'integer',
        'input_data'       => 'array',
        'metadata'         => 'array',
        'calculated_at'    => 'datetime',
    ];

    // =========================================================================
    // RELATIONSHIPS
    // =========================================================================

    /**
     * Risk score belongs to a district.
     */
    public function district()
    {
        return $this->belongsTo(District::class, 'district_id');
    }

    /**
     * Risk score has many alerts.
     * One risk score can trigger multiple alerts
     * (e.g. one per organization or program).
     */
    public function alerts()
    {
        return $this->hasMany(Alert::class, 'risk_score_id');
    }

    // =========================================================================
    // QUERY SCOPES
    // =========================================================================

    /**
     * Scope: filter by hazard type.
     */
    public function scopeForHazard($query, string $hazard)
    {
        return $query->where('hazard_type', $hazard);
    }

    /**
     * Scope: filter HIGH risk scores only.
     * Score >= 7.0 is HIGH per our methodology.
     */
    public function scopeHighRisk($query)
    {
        return $query->where('score', '>=', 7.0);
    }

    // =========================================================================
    // HELPERS
    // =========================================================================

    /**
     * Get human-readable risk level from score.
     *
     * Thresholds aligned with CholeraRiskEngine:
     *   HIGH   → score >= 7.0
     *   MEDIUM → score >= 4.0
     *   LOW    → score < 4.0
     *
     * @return string HIGH | MEDIUM | LOW
     */
    public function getRiskLevelAttribute(): string
    {
        if ($this->score >= 7.0) return 'HIGH';
        if ($this->score >= 4.0) return 'MEDIUM';
        return 'LOW';
    }

    /**
     * Get reason from metadata if available.
     *
     * @return string
     */
    public function getReasonAttribute(): string
    {
        return $this->metadata['reason'] ?? 'No reason provided';
    }
}