<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Risk scores - calculated risk assessments.
     * 
     * Generated by risk engines (Python FastAPI).
     * Stored for historical tracking and analysis.
     * 
     * Example:
     * District: Mora
     * Hazard: Cholera
     * Score: 7.84/10 (HIGH)
     * Timestamp: 2026-03-15 09:30:00
     * 
     * Triggers alert if score > threshold.
     */
    public function up(): void
    {
        Schema::create('risk_scores', function (Blueprint $table) {
            $table->uuid('id')->primary();

            // What and where
            $table->uuid('district_id');
            $table->uuid('hazard_type_id');

            // Risk assessment
            $table->decimal('score', 5, 2); // 0.00 to 100.00 (we use 0-10 scale)
            $table->enum('risk_level', ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL']);

            // Why this score?
            $table->text('reason')->nullable();
            $table->integer('children_at_risk')->nullable();
            $table->integer('time_window_days')->nullable(); // urgency window

            // Input data that produced this score
            $table->jsonb('input_data')->nullable();

            // Risk engine details
            $table->string('risk_engine', 100)->nullable(); // cholera_v1, heat_v2
            $table->string('engine_version', 20)->nullable();

            // Who/what calculated this?
            $table->uuid('calculated_by_user_id')->nullable();
            $table->string('calculation_source', 50)->nullable(); // api, scheduled, manual

            // When calculated
            $table->timestamp('calculated_at');

            // Did this trigger an alert?
            $table->uuid('alert_id')->nullable();

            // Metadata for additional context
            $table->jsonb('metadata')->nullable();

            $table->timestamps();
            $table->softDeletes();

            // Foreign keys
            $table->foreign('district_id')
                ->references('id')
                ->on('districts')
                ->onDelete('cascade');

            $table->foreign('hazard_type_id')
                ->references('id')
                ->on('hazard_types')
                ->onDelete('cascade');

            $table->foreign('calculated_by_user_id')
                ->references('id')
                ->on('users')
                ->onDelete('set null');


            // Indexes
            $table->index('district_id');
            $table->index('hazard_type_id');
            $table->index('risk_level');
            $table->index('score');
            $table->index('calculated_at');

            // Track latest score per district/hazard
            $table->index(['district_id', 'hazard_type_id', 'calculated_at']);
        });

    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('risk_scores');
    }
};
